### ISSUE TITLE
Executing sugar-runner through the Run Command fails

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/sugar-runner#4]
Using run command in GNOME, KDE or XFCE (Alt+F2), fails with an unexpected reason. Pointed out by Sebastian on the mailing list. Confirmed on a native build of Ubuntu 20.04 Focal Fossa

**Comment by quozl** [comment]
http://lists.sugarlabs.org/archive/sugar-devel/2020-February/057741.html

**Comment by srevinsaju** [comment]
This is related to `nohup`. `sugar-runner` command cannot be run through the run command, other than the terminal (as of now)

**Comment by chimosky** [comment]
Sugar-runner now runs fine.
